"""
Storage Layer: SQL Seed Generation, Dry-Run Exporter, and Idempotent Ingestion
"""

import json
from typing import List, Dict, Any, Optional
from pahami_data.schemas.models import EntityRecord, SourceRecord, RegionRecord, PassageChunk, IngestionReport
from pahami_data.sources.registry import list_sources


class LocalLkbStore:
    """In-memory local store for offline retrieval, testing, and benchmark evaluation."""
    def __init__(self):
        self.regions: Dict[str, RegionRecord] = {}
        self.sources: Dict[str, SourceRecord] = {s.source_id: s for s in list_sources()}
        self.entities: Dict[str, EntityRecord] = {}
        self.passages: Dict[str, PassageChunk] = {}

    def upsert_region(self, region: RegionRecord) -> None:
        self.regions[region.region_id] = region

    def upsert_entity(self, entity: EntityRecord) -> None:
        self.entities[entity.entity_id] = entity

    def upsert_passage(self, passage: PassageChunk) -> None:
        self.passages[passage.passage_id] = passage

    def get_entity(self, entity_id: str) -> Optional[EntityRecord]:
        return self.entities.get(entity_id)

    def list_entities_by_region(self, region_id: str) -> List[EntityRecord]:
        return [e for e in self.entities.values() if e.region_id == region_id and e.verification_status == "verified"]


def generate_sql_seed(
    regions: List[RegionRecord],
    sources: List[SourceRecord],
    entities: List[EntityRecord],
    passages: Optional[List[PassageChunk]] = None
) -> str:
    """
    Generates standard PostgreSQL INSERT ... ON CONFLICT DO NOTHING statements
    for seed loading into Supabase without requiring external Python runtime.
    """
    lines = [
        "-- ====================================================================",
        "-- SEED DATA: Local Knowledge Base (LKB) Karesidenan Madiun",
        "-- Auto-generated by Pahami Data Pipeline CLI",
        "-- ====================================================================",
        "",
        "BEGIN;",
        ""
    ]

    # Regions
    lines.append("-- 1. Regions")
    for r in regions:
        p_name = f"'{r.popular_name}'" if r.popular_name else "NULL"
        p_parent = f"'{r.parent_id}'" if r.parent_id else "NULL"
        lines.append(
            f"INSERT INTO lkb_regions (region_id, name, popular_name, level, parent_id, code_source) "
            f"VALUES ('{r.region_id}', '{r.name}', {p_name}, '{r.level}', {p_parent}, '{r.code_source}') "
            f"ON CONFLICT (region_id) DO UPDATE SET name = EXCLUDED.name, popular_name = EXCLUDED.popular_name;"
        )
    lines.append("")

    # Sources
    lines.append("-- 2. Sources")
    for s in sources:
        clean_title = s.title.replace("'", "''")
        clean_pub = s.publisher.replace("'", "''")
        lines.append(
            f"INSERT INTO lkb_sources (source_id, publisher, title, url, retrieved_at, license, attribution_note, import_mode) "
            f"VALUES ('{s.source_id}', '{clean_pub}', '{clean_title}', '{s.url}', '{s.retrieved_at}', '{s.license}', '{s.attribution_note or ''}', '{s.import_mode}') "
            f"ON CONFLICT (source_id) DO NOTHING;"
        )
    lines.append("")

    # Entities and Evidence
    lines.append("-- 3. Entities & Evidence")
    for e in entities:
        c_name = e.canonical_name.replace("'", "''")
        s_desc = e.short_description.replace("'", "''")
        e_usage = e.educational_usage.replace("'", "''")
        q_json = json.dumps(e.quantitative_constraints.model_dump() if e.quantitative_constraints else {}).replace("'", "''")
        aliases_pg = "{" + ",".join([f'"{a}"' for a in e.aliases]) + "}"
        grades_pg = "{" + ",".join(str(g) for g in e.grade_suitability) + "}"
        subjects_pg = "{" + ",".join(e.subject_tags) + "}"

        lines.append(
            f"INSERT INTO lkb_entities ("
            f"entity_id, region_id, category, subcategory, canonical_name, aliases, "
            f"short_description, educational_usage, grade_suitability, subject_tags, "
            f"safe_for_word_problem, quantitative_constraints, verification_status, dedup_fingerprint"
            f") VALUES ("
            f"'{e.entity_id}', '{e.region_id}', '{e.category}', '{e.subcategory}', '{c_name}', '{aliases_pg}', "
            f"'{s_desc}', '{e_usage}', '{grades_pg}', '{subjects_pg}', "
            f"{str(e.safe_for_word_problem).lower()}, '{q_json}'::jsonb, '{e.verification_status}', '{e.dedup_fingerprint}'"
            f") ON CONFLICT (entity_id) DO UPDATE SET "
            f"short_description = EXCLUDED.short_description, educational_usage = EXCLUDED.educational_usage;"
        )

        for ev in e.evidence:
            claim_esc = ev.claim.replace("'", "''")
            lines.append(
                f"INSERT INTO lkb_entity_evidence (entity_id, source_id, claim, reviewer, verified_at) "
                f"VALUES ('{e.entity_id}', '{ev.source_id}', '{claim_esc}', '{ev.reviewer}', '{ev.verified_at}');"
            )

    lines.append("")
    lines.append("COMMIT;")
    return "\n".join(lines)
